### ISSUE TITLE
Always whole lines showing, regardless of the selection

### ISSUE THREAD

**Issue by marqmitk** [mistricky/codesnap.nvim#10]
In visual block and visual line mode, the screenshot shows the whole lines and in the last line up to the cursor, not what is actually selected.

![2024-02-23-093959_hyprshot](https://github.com/mistricky/codesnap.nvim/assets/95558991/2f547ec6-4672-472d-85b2-5814c97b3aa3)

![2024-02-23-094024_hyprshot](https://github.com/mistricky/codesnap.nvim/assets/95558991/c31169c5-1a63-4d5e-b220-61957dd95e21)

**Comment by mistricky** [comment]
Hi @marqmitk, thx for your bug report and PRs again! normally code always shows line-by-line, as a code snapshot plugin, is block-visual features snapshot really necessary?

**Comment by marqmitk** [comment]
good point, thought the same thing already, only reason i would find it useful is for consistency, so if its not implemented i would add a notification that it doesn't work or just remove it from the modes that trigger the preview. but you are right that its not really useful for sharing code

**Comment by mistricky** [comment]
I think block-visual may not be for code snapshot, maybe we can add notification about visual block not work at document, and if more suitable scenario about visual block found, then reopen this issue and consider to implement it, how do you think?

**Comment by mistricky** [comment]
Hi @marqmitk, would you want to maintain this project with me? if you want I will add you to collaborators of this project 😉
