### ISSUE TITLE
Way to set the padding size

### ISSUE THREAD

**Issue by s1n7ax** [mistricky/codesnap.nvim#108]
Right now padding of the outer container is pretty thick. Is there a way to shrink it down?

**Comment by s1n7ax** [comment]
Off topic. Just wondering why you didn't make it a neovim plugin in entirety with out breaking it into two, cli application and a plugin that uses the cli application.

**Comment by mistricky** [comment]
Hi @s1n7ax, thx for this issue.
> Right now padding of the outer container is pretty thick. Is there a way to shrink it down?

That's a great idea, I'll consider allowing custom padding config in the future.

> Off topic. Just wondering why you didn't make it a neovim plugin in entirety with out breaking it into two, cli application and a plugin that uses the cli application.

You are right, make the `generator` of CodeSnap as CLI or Library is better, that can wrap as VSCode plugin or something, but CodeSnap written in my spare time, I don't have energy to do these things right now, if someone can PR for this things, I'll appreciate :)

**Comment by mistricky** [comment]
Hi @s1n7ax, CodeSnap now supports customize background padding of snapshot, upgrade to v1.4.1 and follow https://github.com/mistricky/codesnap.nvim?tab=readme-ov-file#customize-background-padding to get start. Thx for the issue reporting again. :)

**Comment by s1n7ax** [comment]
@mistricky  Type I guess `bg_padding = null`. It should be `nil` right?

**Comment by mistricky** [comment]
Oh god, sorry my mind didn't switch language to Lua 😅. You're right, I'll fix the typo later.
