### ISSUE TITLE
No executable codelens found at current line

### ISSUE THREAD

**Issue by idelice** [mistricky/codesnap.nvim#109]
Whenever i select lines of code to snap with the keybinding set, i get that error in the title.

However, if I select the lines of code to snap using the command instead: `<,'>CodeSnap` - it works fine.

Config
```lua
return {
  "mistricky/codesnap.nvim",
  build = "make",
  keys = {
    { "<leader>cc", "<cmd>CodeSnap<cr>", mode = "x", desc = "Codesnap" },
  },
  opts = {
    has_breadcrumbs = true,
    bg_theme = "bamboo",
  },
}
```
What am I doing wrong with the keybinding?

**Comment by mistricky** [comment]
Hi @idelice, thx for the issue reporting, this issue is duplicated with https://github.com/mistricky/codesnap.nvim/issues/103
