### ISSUE TITLE
the plugin is not being detected after adding to plugins

### ISSUE THREAD

**Issue by khatibomar** [mistricky/codesnap.nvim#115]
```
......
  -- add jsonls and schemastore packages, and setup treesitter for json, json5 and jsonc
  { import = "lazyvim.plugins.extras.lang.json" },

  -- add any tools you want to have installed below
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
      },
    },
  },
  -- https://github.com/mistricky/codesnap.nvim
  {
    "mistricky/codesnap.nvim",
    build = "make",
  },
}
```

I opened and closed nvim, and still can't run snapshot command nor they are available in autocomplete.

my `nvim --version`

```
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
```

I am on fedora sway 40, and I have Rust installed.

**Comment by mistricky** [comment]
Hi @khatibomar, thx for this issue report. What's your architecture? x86 or ARM? 

> I opened and closed nvim, and still can't run snapshot command nor they are available in autocomplete.

What error message you get when you try to run `CodeSnap` command?

**Comment by khatibomar** [comment]
```
E492: Not an editor command: CodeSnap
```

architecture `6.8.5-301.fc40.x86_64`

**Comment by mistricky** [comment]
It seems like you are not install CodeSnap successful, type `:Lazy` to ensure you have installed CodeSnap

**Comment by khatibomar** [comment]
I did, it's not not being detected.

I searched entire Insall/Update/Sync lists for `CodeSnap` no pattern match.

**Comment by khatibomar** [comment]
I also tested now on Mac book M3 pro same thing, command not found

**Comment by khatibomar** [comment]
tried also adding `make build_generator` in Linux, no signs of life so far

**Comment by mistricky** [comment]
🤔️ I think it's nothing to do with CodeSnap, can you make a clean config and install CodeSnap try again?

**Comment by khatibomar** [comment]
@mistricky I did a fresh install for lazyvim, same thing can't detect

**Comment by khatibomar** [comment]
@mistricky I tried now also in virtual machine linux mint, on fresh install for neovim and lazyvim install.
I figured out what I was doing wrong.

placing the plugin in second return, Lazy vim wasn't able to detect it

![image](https://github.com/user-attachments/assets/697603f5-0af6-431f-b277-05a543f23e2e)

When I place it here it worked, before I was placing it in the second return brackets

![image](https://github.com/user-attachments/assets/f62bf612-4633-4a7e-9491-fd3d57617c8d)

**Comment by mistricky** [comment]
Now CodeSnap works properly?

**Comment by khatibomar** [comment]
Yup, we can close I think
