### ISSUE TITLE
CodeSnapASCII not saving anything in clipboard

### ISSUE THREAD

**Issue by Reledia** [mistricky/codesnap.nvim#116]
Hello. As by description, CodeSnap seems to work wonderfully except for the CodeSnapASCII command. The info popup informs me that all went good, but in the clipboard (even if emptied beforehand) has only my previous content, no ASCII screenshot. I am using NVIM v0.11.0-dev-358+g6a886a251 on EndevourOS

**Comment by mistricky** [comment]
Hi @Reledia, thx for the issue report, can you test with v1.5.1?

**Comment by Reledia** [comment]
It's perfect now, thanks!
