### ISSUE TITLE
Neovim crashes when using codesnap with rust code

### ISSUE THREAD

**Issue by augustocdias** [mistricky/codesnap.nvim#118]
When I call `:CodeSnap` on rust code, neovim crashes. 

![t-rec_1](https://github.com/mistricky/codesnap.nvim/assets/1080789/a9164724-4255-4aed-826f-4a918aba2d02)

Here's the repo where this code resides: https://github.com/wireapp/core-crypto

**Comment by mistricky** [comment]
https://github.com/mistricky/codesnap.nvim/assets/22574136/27c0589f-fe66-4b89-8732-2b5436d16f32

I'm not sure what's happen, I can't reproduce on my computer.

Can you provide the following information to help us to debug:

1. What's your architecture x86 or ARM?
2. What's version of Neovim do you use?
3. What's version of CodeSnap.nvim do you use?

**Comment by augustocdias** [comment]
on ARM. Mac M1 Pro

NVIM v0.11.0-dev-364+g73ae7d44a
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189

Its the latest main. I had just installed yesterday when I was trying. It does work with lua though...

![image](https://github.com/mistricky/codesnap.nvim/assets/1080789/27393725-4f95-4387-bdef-478c95682dc1)

**Comment by mistricky** [comment]
I can't reproduce, can you make a new clean Neovim config and install CodeSnap.nvim and try again?

**Comment by augustocdias** [comment]
I'm currently away from home. I'll try again on Monday.

**Comment by augustocdias** [comment]
It stopped happening... I think we can close this. If I make a way to reproduce it I'll reopen and give more details
