### ISSUE TITLE
The :CodeSnap won't work

### ISSUE THREAD

**Issue by Hareekshith** [mistricky/codesnap.nvim#134]
Using `:lua require("codesnap").copy_into_clipboard()`:
![image](https://github.com/user-attachments/assets/797a5fb1-bc66-4220-b168-c856befd2e12)

Using `:'<,'>CodeSnap`: 
![image](https://github.com/user-attachments/assets/e2c71822-2aaf-4627-97f3-2bee57d9abf6)

Where did I install wrong? Or what exactly is the problem I am facing

**Comment by mistricky** [comment]
@Hareekshith CodeSnap uses an external module to generate code snapshots which called `generator`. CodeSnap cross-compile the following three target platform by default:
- x86_64-unknown-linux-gnu
- x86_64-apple-darwin
- aarch64-apple-darwin

so if your OS is in the above target list, you should add the build option in your install config, for example Lazy.nvim:
```lua
{ "mistricky/codesnap.nvim", build = "make" }
```

But if your OS is not in the target list, you should update the build option to `make build_generator` to compile the `generator` from source, like

```lua
{ "mistricky/codesnap.nvim", build = "make build_generator" }
```

Please note that CodeSnap does not support Windows yet.

**Comment by Hareekshith** [comment]
I am doing this in nvchad, the format you have given me is not matching with that of init.lua in plug-ins of nvchad. Where do I put the command? Please guide me, I'm new to this and here to have an experience of nvim.

**Comment by mistricky** [comment]
@Hareekshith I'm not using NvChad but follow the [document](https://nvchad.com/docs/config/plugins), seems like the NvChad use Lazy.nvim as package manager by default, so maybe you can config like this:

```lua
return {
 { "mistricky/codesnap.nvim", build = "make build_generator" },
  -- ... your other NvChad plugin config
}
```

Please make sure you have Rust dev env before you execute make build_generator

**Comment by Hareekshith** [comment]
![image](https://github.com/user-attachments/assets/b1d1f319-33af-4186-9109-e0c7679aaf22)
Here is what I am getting while installing and, 
![image](https://github.com/user-attachments/assets/3c406028-0c12-4170-bf27-8c66078c7e7d)
Here is my init.lua (plugins) for nvchad

**Comment by retrouser955** [comment]
@Hareekshith do you have rust installed?

**Comment by Hareekshith** [comment]
I have go install since I am using yay

**Comment by mistricky** [comment]
@Hareekshith This is due to compile source code is taking too much time on your computer, since `Lazy.nvim` has a default timeout period for the build stage, if you taking too much time on compilation, `Lazy.nvim` will throw an error:
```
Process was killed because it reached the timeout
```

There is two solutions:
1. Increase the timeout value of Lazy.nvim, you can read the [document](https://lazy.folke.io/configuration) for more detail, you need to pay attention to the `git.timeout` field.
2. Just like I mentioned above, CodeSnap has precompiled generator for three platform, if your OS is in the following list:
- x86_64-unknown-linux-gnu
- x86_64-apple-darwin
- aarch64-apple-darwin

  You can use `make` instead of `make build_generator`, like:
```lua
return {
 { "mistricky/codesnap.nvim", build = "make" },
  -- ... your other NvChad plugin config
}
```

**Comment by Hareekshith** [comment]
After doing that the plugin got installed, but is giving me with this
![image](https://github.com/user-attachments/assets/eca6ce0c-581c-44ea-9d37-0a971cbc32b1)

**Comment by Hareekshith** [comment]
Never-mind the problem got fixed when I created a custom.lua and setup the plug in! 

Is there any way to reduce the corner curves of the code window?
