### ISSUE TITLE
Not working with a Windows Subsystem for Linux

### ISSUE THREAD

**Issue by JuanGdev** [mistricky/codesnap.nvim#36]
I am using a WSL with Ubuntu, I followed all the installation steps correctly, but when I run the `CodeSnapPreviewOn` command, I get the message of the image, I am not an expert in these matters :(

![image](https://github.com/mistricky/codesnap.nvim/assets/73394216/adee627b-5ed6-4ee4-9dba-d02a949b9ef0)

**Comment by mistricky** [comment]
Sorry for the late reply, these weeks codesnap.nvim undergone a refactor, can you try again with latest version?

**Comment by JuanGdev** [comment]
No problem, it is understandable that there is a lot of work. I'm on the lookout for anything!
I have updated it and I still get the error message, I am attaching screenshots of the updated pluggin and the error message.

![image](https://github.com/mistricky/codesnap.nvim/assets/73394216/b71e86d1-dafd-46c9-8a30-1f307050fb1a)

**Comment by mistricky** [comment]
I'm not familiar with Windows & WSL, but the error describe that the HTTP request send to HTTPS port, do you use proxy tools?

**Comment by mistricky** [comment]
Hi! CodeSnap was refactor, you can reinstall follow the latest README, if have any problem just let me know

**Comment by JuanGdev** [comment]
Hi @mistricky . I update the plugin but I'm getting some errors trying to build again
![image](https://github.com/mistricky/codesnap.nvim/assets/73394216/2ab1ab9a-1adf-4b18-a1f9-12bf7fc570af)
![image](https://github.com/mistricky/codesnap.nvim/assets/73394216/76a6cc35-efd2-429f-90c8-4c8c655f9b30)

**Comment by jacobrreed** [comment]
@JuanGdev Try manually cleaning the package, in Lazy go to the codesnap and press `x` to force uninstall, then press `I` to reinstall. CodeSnapPreviewOn isnt support anymore either so make sure you follow the README in master

**Comment by jacobrreed** [comment]
> Thank you @jacobrreed ! Now I can save pictures but I can't either copy to clipboard in Windows like you mentioned on Issue #73 ![CodeSnap_2024-04-23_at_220316](https://private-user-images.githubusercontent.com/73394216/325076052-72b89aa6-f62d-4c80-b48f-771db563faa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzE5NjYsIm5iZiI6MTcxMzkzMTY2NiwicGF0aCI6Ii83MzM5NDIxNi8zMjUwNzYwNTItNzJiODlhYTYtZjYyZC00YzgwLWI0OGYtNzcxZGI1NjNmYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MDc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjIyNGMxY2JiN2VhNzIxN2M4ZjIzYjAyYjQwMWZlYjM1MTkzZWJiNDYwOTVhZTYyZTA0ZjU1NzE0NzQ4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPNEboC1vkIob5qNYaOdZCa9wqowxzChVO2ZpwU6yA0)
> 
> I will close this Issue and follow the progress of the one you have opened!

Nice , ya I think that needs some actual work.
