### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by Toni500github** [mistricky/codesnap.nvim#42]
![image](https://github.com/mistricky/codesnap.nvim/assets/88878648/e1bd0cfe-8271-406e-8373-49a3c6b705b6)

looks like `libgenerator.dylib` doesn't exists, but `libgenerator.so` does

![image](https://github.com/mistricky/codesnap.nvim/assets/88878648/eaf67809-a13d-48a6-811a-75c2b2d464d2)

**Comment by mistricky** [comment]
Hi @Toni500github thx for bug report, this issue is duplicates https://github.com/mistricky/codesnap.nvim/issues/39
