### ISSUE TITLE
Not working on windows os(not wsl)

### ISSUE THREAD

**Issue by soullessness1611** [mistricky/codesnap.nvim#48]
Hi

I have issue as below figure, I not sure it's supported windows os (neovim on windows not wsl) 

![image](https://github.com/mistricky/codesnap.nvim/assets/131554043/15948125-94b5-4e56-afe9-c1aceb78d5f1)

**Comment by mistricky** [comment]
Sorry, this plugin is not supported on Windows yet, but have planned to support WSL, you can follow [this issue](https://github.com/mistricky/codesnap.nvim/issues/36) for more detail

**Comment by KevinNitroG** [comment]
Hi, can you develop it to support Windows? The image exported from your plugin is really nice, and I really love it 🥰

**Comment by mistricky** [comment]
I'm not familiar with Windows, It may take a long time to support it

**Comment by pidgeon777** [comment]
> I'm not familiar with Windows, It may take a long time to support it

A Windows port would be great 👍.

**Comment by soullessness1611** [comment]
> I'm not familiar with Windows, It may take a long time to support it

I can wait for you release version support windows os.
