### ISSUE TITLE
require("codesnap.nvim").setup() didn't work

### ISSUE THREAD

**Issue by goombaActivist** [mistricky/codesnap.nvim#5]
Hello, amazing plugin 😍, really missing a feature like that for Neovim, however I had issues running the Lua module
this didn't work for me using Lazy as plugin manager,
```lua
require("codesnap.nvim").setup({})
```
but this did
```lua
require("codesnap").setup({})
```

this might be a Lazy only behavior, so feel free to close this issue.

**Comment by mistricky** [comment]
Hi! thx for use this plugin and report this issue, this seems like there is a mistake in the document, I'll fix it as soon as possible
