### ISSUE TITLE
save_path is not a path but a specific filename

### ISSUE THREAD

**Issue by dch** [mistricky/codesnap.nvim#59]
I was expecting `save_path` to take a directory as parameter, not a specific filename.

e.g. `save_path = /home/me/snapshots/"`

and for it to auto-generate filenames for that directory.

Instead it seems to take a specific named file only:

```
require("codesnap").setup({
	save_path = "/tmp/snap.png"
})
```

Which seems a lot less useful?

Could we either add a `auto_save_dir` parameter which does what I expected, or is
it possible to change the behaviour for save_path, after it's been shipped?

**Comment by mistricky** [comment]
Hi there, sounds a great idea, but what should be the auto-generate filename?

**Comment by mistricky** [comment]
The `CodeSnapSave` command act like download, whenever you use browser or something download file, the browser will always prompt a dialog to ask you to enter the desired filename for downloading or the filename is already specified by that website.

If we provide a save_path parameter for CodeSnapSave command, would it be better? like:
```shell
CodeSnapSave ~/Pictures/xxxx.png
```

If you not pass the save_path to CodeSnapSave, the CodeSnap.nvim will read the `save_path` item in config instead.
```shell
CodeSnapSave
```

**Comment by vinniefranco** [comment]
You could have a sane default and allow a config to override it. Use strftime formatting to do something like `"Codesnap-%Y-%m-%d-%H%M%S.png"`
