### ISSUE TITLE
:CodeSnap command not copying anything on X11 KDE Plasma

### ISSUE THREAD

**Issue by yoyobara** [mistricky/codesnap.nvim#69]
this seems to be somehow related to the `arboard` library.

see my issue [there.](https://github.com/1Password/arboard/issues/143)

**Comment by mistricky** [comment]
Thx for opening this issue for X11 KDE plasma, I'm using Hyprland Wayland, and I haven't tested CodeSnap.nvim on this DE, If you're interested, can u help me to track this issue and test it?

**Comment by Uzaaft** [comment]
@yoyobara  Is the issue solved now?

**Comment by yoyobara** [comment]
@Uzaaft yeah it seems to work now. thanks!
