### ISSUE TITLE
Easier way to detect language type?

### ISSUE THREAD

**Issue by jacobrreed** [mistricky/codesnap.nvim#74]
Currently doing this:
```
    {
      "<leader>ss",
      function()
        vim.cmd("CodeSnap " .. vim.bo.filetype)
      end,
      desc = "CodeSnap",
      mode = "v",
    },
    {
      "<leader>sS",
      function()
        vim.cmd("CodeSnapSave " .. vim.bo.filetype)
      end,
      desc = "CodeSnap save to ~/codesnap",
      mode = "v",
    },

```

Seems to work.. for lua at least, might work for other languages, I guess it depends how the names are matched vs vim.bo.filetype

**Comment by mistricky** [comment]
That's good point, thx for your advice

**Comment by mistricky** [comment]
Hi @jacobrreed  after refactoring, you don't need to pass the filetype explicitly, CodeSnap will auto-detect what syntax the file should be used for highlighting code.

**Comment by jacobrreed** [comment]
> Hi there, @jacobrreed looks like the above Lua code snapshot highlight is working properly, can you provide a further description of the issue you're encountering? 

Oh uh.. ya I think I'm so used to my color scheme that the colors threw me off
