### ISSUE TITLE
Tab indention doesn't look right.

### ISSUE THREAD

**Issue by alexxShandsome** [mistricky/codesnap.nvim#76]
I use tabs for indention and it looks like this.
![image](https://github.com/mistricky/codesnap.nvim/assets/77670158/207d3001-d27f-463c-a32b-d8b0d60397e6)

It works fine for spaces.

This is my ```nvim --version```
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by mistricky** [comment]
Hi @alexxShandsome, thx for reporting the issue, I have fixed it and released it along with v1.1.10, can you test this bug in v1.1.10? If it still not working properly, please let me know, thx.

**Comment by alexxShandsome** [comment]
It works fine now, thank you.
![codesnap](https://github.com/mistricky/codesnap.nvim/assets/77670158/4226229a-756a-464d-abd9-7bb1a4e1b328)

Well another problem for me is the text wrapping. I hope it can be improved in the future.

**Comment by Uzaaft** [comment]
@mistricky  This should be closed now since the issue seems to be resolved.
