### ISSUE TITLE
 Question about configuring padding for code screenshots 

### ISSUE THREAD

**Issue by try-to-fly** [mistricky/codesnap.nvim#80]
I am using a code screenshot plugin in nvim and I’m not sure how to configure the padding for the code screenshot content. Sometimes I want to set the padding to be smaller, or even completely remove it. Is there a way to achieve this configuration? Thank you for your help!

**Comment by mistricky** [comment]
@try-to-fly Hi there, sorry CodeSnap doesn't have such options to config padding.
