### ISSUE TITLE
Code highlighting in PHP is... weird?

### ISSUE THREAD

**Issue by nexxai** [mistricky/codesnap.nvim#81]
I apologize for the less than descriptive title, but let me explain with screenshots.

Let's say I have this PHP class:
<img width="948" alt="Screenshot 2024-04-08 at 10 04 55 PM" src="https://github.com/mistricky/codesnap.nvim/assets/4316564/0e08a504-5430-4f14-8af6-f9d3d5bc4419">

If I select this text:
<img width="636" alt="Screenshot 2024-04-08 at 10 05 31 PM" src="https://github.com/mistricky/codesnap.nvim/assets/4316564/e27a8a5a-0694-4f5b-9b6d-07b906a8958d">

the highlighting works perfectly:
![faaa5d4c-b43f-4522-a984-0ed4652d1bcb](https://github.com/mistricky/codesnap.nvim/assets/4316564/9d0b6e58-1085-4e28-9162-700261e49973)

But if I simply miss including the `<?php` tag at the top of every PHP file in the selection:
<img width="564" alt="Screenshot 2024-04-08 at 10 06 38 PM" src="https://github.com/mistricky/codesnap.nvim/assets/4316564/799e1a10-fd50-4138-948b-368aef8d09d7">

Everything stays dark:
![71b59030-99bf-471a-bbab-91d0e5422e08](https://github.com/mistricky/codesnap.nvim/assets/4316564/2ab43787-3945-4d5d-a473-605bc6b48cc9)

Now, OK, at first glance it seems like it's using the opening tag to figure out the language, and since it isn't sure, it doesn't do anything, but it does highlight *very* common coding words but only ever in PHP DocBlock comments:
![82062d6c-7ba9-492e-938e-570373f2f081](https://github.com/mistricky/codesnap.nvim/assets/4316564/9cecd10d-bc5e-4ca2-acca-452fe3b9bb92)

Is there anything I can do about this, or am I just kind of stuck?

**Comment by mistricky** [comment]
Seems like this issue is related to https://github.com/mistricky/codesnap.nvim/issues/67

**Comment by mistricky** [comment]
The syntax highlighting is implements by syntect, I just figure it out, the syntect have two diffience language type names "PHP" & "PHP Source", if need to highlight PHP code snippet should use "PHP Source" instead of "PHP".

**Comment by mistricky** [comment]
I'm already improve the strategy of highlight PHP filetype, can you test this issue with the latest version of CodeSnap.nvim (v1.1.12)? if there still have any problem, please let me know. @nexxai Thx for this issue report

**Comment by nexxai** [comment]
![image](https://github.com/mistricky/codesnap.nvim/assets/4316564/ec09ef58-0dc5-45c7-85d6-04a7bac737b6)

Looks perfect.  Thanks!
