### ISSUE TITLE
Bug: Version v1.1.10 and upper fail on Mac

### ISSUE THREAD

**Issue by Michaelpalacce** [mistricky/codesnap.nvim#82]
Not sure what exactly happens, but from what I can tell, neovim just quits... here is an example...

https://github.com/mistricky/codesnap.nvim/assets/17056014/6e7c0f35-0243-4c3f-bfed-f8a22167965e

Same does not happen on v1.1.9

https://github.com/mistricky/codesnap.nvim/assets/17056014/569b4666-0bbd-4596-a929-a23c9d392951

Configuration:

```lua
return {
	{
		"mistricky/codesnap.nvim",
		build = "make",
		version = "v1.1.x",
		config = function()
			require("codesnap").setup({
				mac_window_bar = true,
				title = "CodeSnap.nvim",
				code_font_family = "CaskaydiaCove Nerd Font",
				watermark_font_family = "Pacifico",
				watermark = "",
				bg_theme = "grape",
				breadcrumbs_separator = "/",
				has_breadcrumbs = true,
			})
		end,
	}
}
```

Notes:
- This happens on v1.1.11 too
- macbook: <img width="278" alt="image" src="https://github.com/mistricky/codesnap.nvim/assets/17056014/e014aa27-9625-4050-831b-2922d290f801">

Troubleshooting:
- Restarted the terminal
- Restarted the PC

**Comment by mistricky** [comment]
Hi there, @Michaelpalacce  thx for this issue report, if I understand correctly this issue describes that the CodeSnap v1.1.9 works properly, but when upgraded to v1.1.10 or the upper version, CodeSnap crashes.

I can't reproduce it on my Mac M1, do you have tried clearing CodeSnap and reinstalling it? Does it work fine?

**Comment by mistricky** [comment]
This issue seems out of stale, if you reproduce this bug or if there need to any helps, I will reopen it.
