### ISSUE TITLE
No theme option

### ISSUE THREAD

**Issue by star-light-nova** [mistricky/codesnap.nvim#87]
I didn't like the backgrounds. I just wanted a solid codesnippet, without backgrounds.
I just added this to the `theme`:

```rs
"none" => vec![
                GradientStop::new(0., Color::from_rgba8(0, 0, 0, 0))
            ],

```

Example:
![with_background](https://github.com/mistricky/codesnap.nvim/assets/52784852/a44c7584-5484-42fb-ae35-0478376a640f)
![no_background](https://github.com/mistricky/codesnap.nvim/assets/52784852/c5ed9e6b-b4b8-4b8d-94ca-76587c442972)

Try to drag the image and you will see the difference.

**Comment by star-light-nova** [comment]
Actually, would be better to have an image width and height aligned to the snippet's box, but I have no knowledge in Rust Programming Language.

**Comment by mistricky** [comment]
Hi @star-light-nova, thx for the issue reporting. Actually, it's easy to provide a feature to take code snapshots without background, however, there are some scenarios that need to be considered. 

The purpose of background to provide a specific color or visual appearance, if no background is provide, we also need to support custom code theme and custom background of code snippet window to fit different background in real life. So take code snapshot without background will be support in the future, but not for now.

**Comment by star-light-nova** [comment]
Hi @mistricky.

Thank you for your reply. Understood.

Appreciate it.
