### ISSUE TITLE
Add option to support line numbers

### ISSUE THREAD

**Issue by Dmusulas** [mistricky/codesnap.nvim#88]
I believe a viable enhancement to this plugin would be addition of the option to show line numbers in the screenshot. It might help when not whole file is screenshotted but rather a section of it. When creating guides online or sharing code snaps with others it helps whomever is reading to orient themselves in the file.

**Comment by mistricky** [comment]
Hi @Dmusulas, thx for the issue reporting, line numbers are supported in v1.2.0, you can upgrade CodeSnap.nvim to v1.2.0 and add `has_line_number = true` to open display line numbers feature.

![image](https://github.com/mistricky/codesnap.nvim/assets/22574136/43d3d062-6336-496b-b20d-6e7445d23770)
