### ISSUE TITLE
Add `workspace` 

### ISSUE THREAD

**Issue by Mr-LLLLL** [mistricky/codesnap.nvim#93]
share code snippet to others. workspace is good to show this code blong to some project.

**Comment by Mr-LLLLL** [comment]
I think implement this will be simply. just custom function to get current workspace. maybe i will submit a PR, if i have some time.

**Comment by mistricky** [comment]
Hey @Mr-LLLLL thx for the issue reporting, If I understand correctly, do you mean add CWD name to breadcrumbs? It would be great if users could config whether they want to display CWD name. I tend to provide a config item named `show_breadcrumbs_cwd_name`, default as false, if any user wants to display CWD name, just open it by set it to true.

It would be great if you want to contribute to this feature. To display CWD name, you may need to check this function implementation:

![image](https://github.com/mistricky/codesnap.nvim/assets/22574136/881e6ff9-236a-4e49-a151-86e7ae3af000)

**Comment by Mr-LLLLL** [comment]
> Hey @Mr-LLLLL thx for the issue reporting, If I understand correctly, do you mean add CWD name to breadcrumbs? It would be great if users could config whether they want to display CWD name. I tend to provide a config item named `show_breadcrumbs_cwd_name`, default as false, if any user wants to display CWD name, just open it by set it to true.
> 
> It would be great if you want to contribute to this feature. To display CWD name, you may need to check this function implementation:
> 
> ![image](https://private-user-images.githubusercontent.com/22574136/326261220-881e6ff9-236a-4e49-a151-86e7ae3af000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQ3NzYsIm5iZiI6MTcxNDMxNDQ3NiwicGF0aCI6Ii8yMjU3NDEzNi8zMjYyNjEyMjAtODgxZTZmZjktMjM2YS00ZTQ5LWExNTEtODZlN2FlM2FmMDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOWEwYjMzY2RmMzE0YTVkMjlkYTViMjIzYzk0MDJkZWY1YjIxY2YyY2IzYTFiNTRlYzY2YWRkZGE4ZThjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BojJBoFqv79o7MEGWN8ZEsnA5e7r9-x7UaYkLHzHESY)

Good idea. i wll be submit PR in someday.

**Comment by mistricky** [comment]
Hey @Mr-LLLLL, the workspace implementation has already in latest(v1.3.1), can you test it in latest version?

**Comment by Mr-LLLLL** [comment]
thank you very much. it nice to show `workspace` now.
